FootballShare.Web/Controllers/BettingController.cs
using FootballShare.DAL.Exceptions;
using FootballShare.DAL.Services;
using FootballShare.Entities.Betting;
using FootballShare.Entities.Leagues;
using FootballShare.Entities.Pools;
using FootballShare.Entities.Users;
using FootballShare.Web.Extensions;
using FootballShare.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FootballShare.Web.Controllers
{
    public class BettingController : Controller
    {
        /// <summary>
        /// Betting service object
        /// </summary>
        private IBettingService _bettingService;
        /// <summary>
        /// Pool service object
        /// </summary>
        private IPoolService _poolService;
        /// <summary>
        /// User Manager object
        /// </summary>
        private UserManager<SiteUser> _userManager;

        /// <summary>
        /// Creates a new <see cref="BettingController"/> instance
        /// </summary>
        /// <param name="bettingService">Betting service instance</param>
        /// <param name="poolService">Pool service instance</param>
        /// <param name="userManager">User Manager instance</param>
        public BettingController(IBettingService bettingService, IPoolService poolService, UserManager<SiteUser> userManager)
        {
            this._bettingService = bettingService;
            this._poolService = poolService;
            this._userManager = userManager;
        }

        // GET: Betting/Cancel/5
        [HttpGet("Betting/Cancel/{id:int}")]
        public async Task<ActionResult> Cancel(int id)
        {
            // Confirm current user owns the bet
            SiteUser user = await this._userManager.GetUserAsync(HttpContext.User);
            Wager wager = await this._bettingService.GetWagerAsync(id.ToString());

            if (wager.SiteUserId == user.Id)
            {
                // Get event and return data
                WeekEvent weekEvent = await this._bettingService.GetWeekEventAsync(wager.WeekEventId);

                BettingCancelViewModel vm = new BettingCancelViewModel
                {
                    Event = weekEvent,
                    Wager = wager
                };

                return View(vm);
            }
            else
            {
                return NotFound();
            }
        }

        // POST: Betting/Cancel/5
        [HttpPost("Betting/Cancel/{id:int}")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Cancel(int id, IFormCollection collection)
        {
            // Confirm current user owns the bet
            SiteUser user = await this._userManager.GetUserAsync(HttpContext.User);
            Wager wager = await this._bettingService.GetWagerAsync(id.ToString());

            if (wager.SiteUserId == user.Id)
            {
                try
                {
                    await this._bettingService.RemoveWagerAsync(wager.Id);

                    TempData.Put("UserMessage", new UserMessageViewModel
                    {
                        CssClassName = "alert-success",
                        Title = "Success!",
                        Message = $"Bet cancelled successfully."
                    });

                    return RedirectToAction(nameof(Events), new { seasonWeekId = wager.Event.SeasonWeekId, poolId = wager.PoolId });
                }
                catch
                {
                    TempData.Put("UserMessage", new UserMessageViewModel
                    {
                        CssClassName = "alert-danger",
                        Title = "Error",
                        Message = $"Failed to cancel event. Please try again later."
                    });

                    return View(wager);
                }
            }
            else
            {
                return NotFound();
            }
        }

        // GET: Betting/Events/nfl-2019-1/3
        [HttpGet("Betting/Events/{seasonWeekId}/{poolId:int}")]
        public async Task<ActionResult> Events(string seasonWeekId, int poolId)
        {
            // Confirm user belongs to pool
            SiteUser user = await this._userManager.GetUserAsync(HttpContext.User);
            PoolMember userMembership = await this._poolService.GetPoolMemberAsync(poolId, user.Id);

            if (userMembership != null)
            {
                IEnumerable<Spread> events = await this._bettingService.GetWeekSpreadsAsync(seasonWeekId);
                DateTimeOffset lastSpreadUpdate = await this._bettingService.GetWeekSpreadLastUpdateAsync(seasonWeekId);
                IEnumerable<Wager> weekWagers = await this._bettingService.GetUserWagersForWeekByPoolAsync(user.Id, seasonWeekId, poolId);

                // Get SeasonWeek details
                SeasonWeekEventsViewModel vm = new SeasonWeekEventsViewModel
                {
                    EventSpreads = events.ToList(),
                    LastSpreadUpdate = lastSpreadUpdate,
                    PoolMembership = userMembership,
                    WeekWagers = weekWagers.ToList()
                };

                return View(vm);
            }
            else
            {
                return NotFound();
            }
        }

        // GET: Betting/History/nfl-2019-1/3
        [HttpGet("Betting/History/{seasonWeekId}/{poolId:int}")]
        public async Task<ActionResult> History(string seasonWeekId, int poolId)
        {
            // Confirm user belongs to pool
            SiteUser user = await this._userManager.GetUserAsync(HttpContext.User);
            PoolMember userMembership = await this._poolService.GetPoolMemberAsync(poolId, user.Id);

            if (userMembership != null)
            {
                // Get all wagers from the previous week
                IEnumerable<Wager> wagers = await this._bettingService.GetPoolWagersForWeekAsync(poolId, seasonWeekId);
                BettingHistoryViewModel vm = new BettingHistoryViewModel
                {
                    Pool = userMembership.Pool,
                    Wagers = wagers.ToList(),
                    Week = await this._bettingService.GetSeasonWeekAsync(seasonWeekId)
                };

                return View(vm);
            }
            else
            {
                return NotFound();
            }
        }

        // GET: Betting/Place/2/1
        [HttpGet("Betting/Place/{eventId:int}/{poolId:int}")]
        public async Task<ActionResult> Place(int eventId, int poolId)
        {
            // Check if user is part of pool
            SiteUser user = await this._userManager.GetUserAsync(HttpContext.User);
            PoolMember userMembership = await this._poolService.GetUserPoolProfileAsync(user.Id, poolId);

            if (userMembership == null)
            {
                return NotFound();
            }

            // Get event
            WeekEvent weekEvent = await this._bettingService.GetWeekEventAsync(eventId);

            if (weekEvent.Time <= DateTimeOffset.Now)
            {
                TempData.Put("UserMessage", new UserMessageViewModel
                {
                    CssClassName = "alert-warning",
                    Title = "Deadline passed",
                    Message = $"Betting deadline for this event has already passed."
                });

                return RedirectToAction(
                    nameof(Events),
                    new
                    {
                        seasonWeekId = weekEvent.SeasonWeekId,
                        poolId = poolId
                    }
                );
            }

            // Get event spread
            Spread eventSpread = await this._bettingService.GetSpreadForEventAsync(eventId);

            if (!eventSpread.AwaySpread.HasValue || !eventSpread.HomeSpread.HasValue)
            {
                // Spreads have not yet been pulled for this event
                TempData.Put("UserMessage", new UserMessageViewModel
                {
                    CssClassName = "alert-warning",
                    Title = "No Spreads",
                    Message = $"Spreads are not yet available for this event. Please check back soon."
                });

                return RedirectToAction(
                    nameof(Events),
                    new
                    {
                        seasonWeekId = weekEvent.SeasonWeekId,
                        poolId = poolId
                    });
            }

            // Check if user has already submitted their bet limit for the week
            IEnumerable<Wager> wagersForWeek = await this._bettingService
                .GetUserWagersForWeekByPoolAsync(user.Id, weekEvent.SeasonWeekId, poolId);

            if(wagersForWeek.Count() >= userMembership.Pool.WagersPerWeek)
            {
                TempData.Put("UserMessage", new UserMessageViewModel
                {
                    CssClassName = "alert-warning",
                    Title = "Too Many Bets",
                    Message = $"You have already submitted all of your bets for this week. Cancel one to place another."
                });

                return RedirectToAction(
                    nameof(Events),
                    new
                    {
                        seasonWeekId = weekEvent.SeasonWeekId,
                        poolId = poolId
                    }
                );
            }

            // Check if user has already submitted a bet for this Event
            Wager existingWager = wagersForWeek.Where(w => w.WeekEventId == eventId).FirstOrDefault();

FootballShare.Web/Views/Pools/Create.cshtml
@model FootballShare.Web.Models.CreatePoolViewModel

@{
    ViewData["Title"] = "Create Pool";
}

<h1>Create a Pool</h1>

<h4>Pool</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PoolName" class="control-label"></label>
                <input asp-for="PoolName" class="form-control" />
                <span asp-validation-for="PoolName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SeasonId" class="control-label"></label>
                @Html.DropDownListFor(m => m.SeasonId, Model.AvailableSeasons, new { @class = "form-control" })
                <span asp-validation-for="SeasonId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartingBalance" class="control-label"></label>
                <input asp-for="StartingBalance" class="form-control" />
                <span asp-validation-for="StartingBalance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WagersPerWeek" class="control-label"></label>
                <input asp-for="WagersPerWeek" class="form-control" />
                <span asp-validation-for="WagersPerWeek" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to Pools</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FootballShare.Web/Views/Pools/Delete.cshtml
@model FootballShare.Entities.Pools.Pool

@{
    ViewData["Title"] = "Delete " + Model.Name;
    var parameters = new Dictionary<string, string>
    {
        { "id", Model.Id.ToString() }
    };
}

<h1>Delete @Model.Name</h1>
<a asp-action="Edit" asp-all-route-data="parameters">Back to Edit Pool</a>
<div>
    <hr />
    <p>Are you sure you want to delete this pool? <b>All bets made for the season will be lost!</b></p>
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" />
    </form>
</div>

FootballShare.Web/Views/Pools/Details.cshtml
@model FootballShare.Web.Models.PoolDetailsViewModel

@{
    ViewData["Title"] = Model.Pool.Name;
    var parameters = new Dictionary<string, string>
{
        { "id", Model.Pool.Id.ToString() }
    };
}

<div class="alert alert-info">
    <strong>Heads up!</strong>
    All functionality <em>should</em> be working. If you have issues placing a bet, email it to
    <a href="mailto:corygehr@outlook.com">corygehr@outlook.com</a>.
</div>

<h1>@Html.DisplayFor(model => model.Pool.Name)</h1>
<h4>@Html.DisplayFor(model => model.Pool.Season.Name)</h4>
@if (Model.CurrentUserMembership.IsAdmin)
{
    <p>
        @Html.ActionLink("Edit Pool", "Edit", new { id = Model.Pool.Id })
    </p>
}
<hr />
<h5>Current Week</h5>
<table class="table table-striped">
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(model => model.CurrentSeasonWeek.Name)
            </td>
            <td>
                @Html.ActionLink("Place Bets", "Events", "Betting", new { seasonWeekId = Model.CurrentSeasonWeek.Id, poolId = Model.Pool.Id })
            </td>
        </tr>
    </tbody>
</table>
<h5>Standings</h5>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Members[0].User.DisplayName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Members[0].Balance)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Members)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.User.DisplayName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Balance)
                </td>
            </tr>
        }
    </tbody>
</table>
<h5>History</h5>
<table class="table table-striped">
    <tbody>
        @foreach (var item in Model.PreviousSeasonWeeks)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("View Bets", "History", "Betting", new { seasonWeekId = item.Id, poolId = Model.Pool.Id })
                </td>
            </tr>
        }
    </tbody>
</table>
<div>
    <a asp-action="Index">Back to Pool List</a> |
    <a asp-action="Ledger" asp-all-route-data="parameters">View Transaction Ledger</a> |
    @Html.ActionLink("Leave Pool", "Leave", new { id = Model.Pool.Id })
</div>

FootballShare.Web/Views/Pools/Edit.cshtml
@model FootballShare.Entities.Pools.Pool

@{
    ViewData["Title"] = "Edit " + Model.Name;
    var parameters = new Dictionary<string, string>
    {
        { "id", Model.Id.ToString() }
    };
}

<h1>Edit @Html.DisplayFor(modelItem => modelItem.Name)</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" class="form-control" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsPublic" /> @Html.DisplayNameFor(model => model.IsPublic)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="StartingBalance" class="control-label"></label>
                <input asp-for="StartingBalance" class="form-control" />
                <span asp-validation-for="StartingBalance" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WagersPerWeek" class="control-label"></label>
                <input asp-for="WagersPerWeek" class="form-control" />
                <span asp-validation-for="WagersPerWeek" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Details" asp-all-route-data="parameters">Back to Pool Details</a> |
    <a asp-action="Delete" asp-all-route-data="parameters">Delete Pool</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

FootballShare.Web/Views/Pools/Index.cshtml
@using FootballShare.Entities.Pools
@model FootballShare.Web.Models.ListPoolsViewModel

@{
    ViewData["Title"] = "Pools";
}

<h1>Pools</h1>
<p>
    <a asp-action="Create">Create a Pool</a>
</p>
@if (Model.UserPools.Count > 0)
{
    <h3>My Pools</h3>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.UserPools[0].Pool.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserPools[0].Pool.Season.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserPools[0].Balance)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.UserPools)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Pool.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Pool.Season.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Balance)
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", new { id = item.Pool.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

@if (Model.PublicPools.Count > 0)
{
    <h3>Available Pools</h3>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.PublicPools[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PublicPools[0].Season.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PublicPools[0].StartingBalance)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.PublicPools)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Season.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StartingBalance)
                    </td>
                    <td>
                        @Html.ActionLink("Join", "Join", new { id = item.Id })
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

FootballShare.Web/Views/Pools/Leave.cshtml
@model FootballShare.Entities.Pools.PoolMember

@{
    ViewData["Title"] = "Leave " + Model.Pool.Name;
    var parameters = new Dictionary<string, string>
    {
        { "id", Model.Pool.Id.ToString() }
    };
}

<h1>Leave @Html.DisplayFor(model => model.Pool.Name)</h1>
<a asp-action="Details" asp-all-route-data="parameters">Back to Pool</a>
<div>
    <hr />
    <p>Are you sure you want to leave? <b>You will lose all progress for this season!</b></p>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pool.Season.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pool.Season.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Balance)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Balance)
        </dd>
    </dl>
    <form asp-action="View">
        <input type="submit" value="Leave" class="btn btn-danger" />
    </form>
</div>

FootballShare.Web/Views/Pools/Ledger.cshtml
@model FootballShare.Web.Models.PoolLedgerViewModel
@using FootballShare.Entities.Pools

@{
    ViewData["Title"] = Model.Pool.Name;
    var parameters = new Dictionary<string, string>
    {
        { "id", Model.Pool.Id.ToString() }
    };
}

<h1>@Html.DisplayFor(model => model.Pool.Name)</h1>
<h4>Transaction Ledger</h4>
<a asp-action="Details" asp-all-route-data="parameters">Back to Pool</a>
<hr />
<h5>Recent Transactions</h5>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Transaction Date</th>
            <th>Person</th>
            <th>Description</th>
            <th>Starting Balance</th>
            <th>Amount</th>
            <th>New Balance</th>
        </tr>
    </thead>
    <tbody>
        @foreach (LedgerEntry item in Model.Ledger)
        {
            <tr>
                <td>@item.WhenCreated</td>
                <td>@item.User.DisplayName</td>
                <td>@item.Description</td>
                <td>$@item.StartingBalance</td>
                <td>$@item.TransactionAmount</td>
                <td>$@item.NewBalance</td>
            </tr>
        }
    </tbody>
</table>